Microverse 2: Project
Haadiiii/my-portfolio pull request #1
Opened 2022-06-29 20:04 UTC by Haadiiii

## Mobile version skeleton portfolio: project

In this project we:

* Add HTML file with text required.
* Add CSS file with style according to Figma template.
* Adjust the README file according to the project.

2022-06-29 20:42 UTC, Ugboaja-Uchechi requested changes
Hi @Haadiiii , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Your README looks professional 👏 
- Linters are passing ✔️ 
- Nice commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- **Committing your code regularly**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on index.html
> +    </nav>
- [ ] Kindly make sure your `nav` tag is wrapped in a `header` tag as specified in the project requirement which would also make it more semantic and better for screen readers  🙏 .

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on index.html
> +            <h1>WELCOME</h1>
- [ ] Kindly change the tag from an `h1` tag to an `a` tag as specified in the project requirement

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on index.html
> +        <h2 id="why">Hey! I'm Haadii</h2>
- [ ] Please wrap the main title to an `h1` tag instead of an `h2` tag to make it semantic 🙏.

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on index.html
> +        <h3 id="how">I’am a Software Developer</h3>
- [ ] Kindly change the `h3` tag to a `p` tag as specified in the project requirement 🙏.

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on index.html
> +            <img src="./SocialMedia.png" alt="">
- [ ] Please make sure you wrap your social media icons inside of a `ul` tag and each icon is wrapped in a `li` tag🙏.

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on style.css
> +  height: 20%;
- [ ] Your website overflows. Please fix this by adding an `overflow: hidden;` 🙏.

2022-06-29 20:42 UTC, Ugboaja-Uchechi commented on style.css
> +
- [ ] Please make sure your design looks as close as possible to the figma design 🙏 .

Figma Design | Your Design
------------- | -------------
![figma-design](https://user-images.githubusercontent.com/74814780/176540341-57ad83c2-0523-42e3-81e3-bc31b3835f5f.png)  |  ![your-design](https://user-images.githubusercontent.com/74814780/176540294-fdc6f642-026a-4ed3-9cd4-697a6e9fb11f.png)

2022-06-30 08:58 UTC, Haadiiii commented on index.html
> +    </nav>
done, thanks to notify me.

2022-06-30 08:58 UTC, Haadiiii commented on index.html
> +        <h2 id="why">Hey! I'm Haadii</h2>
done

2022-06-30 09:33 UTC, Nemwel-Boniface requested changes
## Hello @Haadiiii  :wave: ,
I am Nemwel your reviewer for this PR :man_beard: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, however, there are still some which aren't addressed yet.

![](https://media.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif)

 ## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 

 ## ♻️ Required Changes ♻️

- [x] As requested by the previous reviewer, kindly note that you are supposed to try and stick to the chosen [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md). Right now, your design still needs some work to be done so that it may look better.

**Your design**
![image](https://user-images.githubusercontent.com/86318284/176643286-f6193bf2-24f8-4aae-8229-8d2bc5aae2eb.png)

**Desired Figma design**
![image](https://user-images.githubusercontent.com/86318284/176643538-f28ad97a-27ac-4e2c-8030-ff647b2ad935.png)

- Once you finish this your project will be ready for approval :partying_face: 

_Check the comments under the review._

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding! :partying_face: 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 09:33 UTC, Nemwel-Boniface commented on index.html
> +                </ul>
[OPTIONAL] Great job making the requested changes. As the social media icons are supposed to host your links to your social media accounts, it would be a good idea to wrap the `<img>` inside of a `<a href="#"></a>` tag. This way, your viewers will be able to click on the links and be directed straight to your social media profiles.
- Just an example of what it could look like consider the following example:
 ```
 <ul>
        <li>< a href="#"><img src="./Group.png" alt=""></a></li> 
 </ul>
```

2022-06-30 10:59 UTC, omarsalem7 requested changes
Hi @Haadiiii , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 10:59 UTC, omarsalem7 commented on index.html
> +         <a href="">WELCOME</a>
- [ ] Kindly make your logo like the one in the template

| Your design  | Figma design|
| ------------- | ------------- |
|![image](https://user-images.githubusercontent.com/53402600/176661025-712e1ece-dce5-4b5d-bb3b-086b71bcccd1.png) | ![image](https://user-images.githubusercontent.com/53402600/176661081-6c204abb-5926-42fc-8509-1336a3a8b9d7.png) |

2022-06-30 12:28 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @Haadiiii  🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great work on making the changes requested by a previous reviewer 👌
- Your project is professional ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- [OPTIONAL] I suggest putting all the pictures into one folder called `images` to make the project more organized 👌

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 12:28 UTC, Bondok6 commented on index.html
> +        <p id="how">I’am a Software Developer</p>
- [OPTIONAL] I suggest you to use a header tag hx (examples: `<h2>`,`<h3>`, etc...) instead of  `<p>` tag

2022-06-30 12:32 UTC, merged