Mcroverse Porfolio Project
Haadiiii/my-portfolio pull request #14
Opened 2022-07-18 18:52 UTC by Haadiiii

## Microverse Portfolio Porject. 🎉 

In this Project we: ⏬ 

- Add an `HTML` file with text, classes, and ids. 👍 
- Add style `CSS` file with Hamburger menu styling accordingly. 👍 
- Add `my.js` and manipulate Menu Accordingly. 👍 
- Add the `Readme` file. 👍

2022-07-18 19:19 UTC, Nemwel-Boniface requested changes
## Hello @Haadiiii          :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have done a tremendous job setting up your mobile navigation bar and styling it :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-18 19:19 UTC, Nemwel-Boniface commented on index.html
>              </div>
Great job styling your portfolio mobile version you have done a great job. However, kindly note that according to the [project's requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md), you are supposed to stick as much as possible to the chosen [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471). Currently your mobile version has the following design deviations from the Chosen Figma design:

- [ ] In your design, the nav links are currently positioned at the center and they are supposed to be positioned at the left side of the screen. Kindly align them to the left so that it matches the chosen Figma design.

- [ ] Kindly note that your mobile menu is supposed to scale to a height of at least 755px according to the chosen Figma design. Kindly make sure to fix this. 

**This is how your design currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/179590128-54231678-c857-425c-93d7-dcd10e8dbd55.png)

**This is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/179591514-f8907907-493a-452b-873b-632b5d341ff7.png)

- [ ] I have also realized that a "welcome" text is not supposed to be there according to the Figma design. Kindly fix this

**Below is what your design currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/179593855-a8136342-eb71-4fee-9d61-0351a5706e3e.png)

**Below is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/179594726-86bf8c6d-bff0-4b80-8564-d95bfd28f2b7.png)

- [ ] There is the "mail" icon currently present in your design which is not supposed to be there according to the chosen Figma design. Kindly remove it for mobile so that it matches the chosen Figma design.

**Below is what your design currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/179598176-fa347f85-b034-4b2d-a22f-21a99ea8b082.png)


**Below is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/179598524-6593bb79-1346-43d5-a1c9-af0ef240d083.png)

2022-07-18 19:19 UTC, Nemwel-Boniface commented on index.html
> +                <div class="cb"><a href="">contact</a></div>
- [ ] Kindly link the links to the corresponding sections of the projects sections so that this might not be a "hanging" link. If you may be in doubt about how to achieve this, kindly have a look at [this wonderful resource](https://www.w3schools.com/html/html_links_bookmarks.asp) for further reading.

2022-07-18 20:23 UTC, Haadiiii commented on index.html
>              </div>
thanks done 👍

2022-07-18 21:01 UTC, codecaiine requested changes
Hi <STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- Good project implementation :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 09:03 UTC, Haadiiii commented on index.html
issues resolved 👍

2022-07-19 09:08 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Haadiiii 

Your project is complete! Great job for making all the required changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors
- mobile menu works as expected

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/M8dw7l8jhQvSAVpawW/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 15:07 UTC, merged