Popup feature
Haadiiii/my-portfolio pull request #15
Opened 2022-07-20 15:12 UTC by Haadiiii

## Microsoft Porfolio Project ⏬ 

In this project we:

- Add `HTML` file with required texts. 👍 
- Add `CSS` file with styling according to Figma template. 👍 
- Add `JS` file with required Variables and DOM. 👍 
- Added `Readme` file. 👍 
- Resolved `linter` Errors. 👍 

😄 👍

2022-07-20 15:43 UTC, mugishasam123 requested changes
Hi @Haadiiii  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![alt](https://media1.giphy.com/media/41AXf9tlMV8ZmRtFhZ/giphy.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Nice use of Github workflow 🥇 
- No linter errors 💯 
- Descriptive PR summary, keep rocking 🚀 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 15:43 UTC, mugishasam123 commented on index.html
> +                                    <li><a href="">html</a></li>
- [ ] Kindly generate the projects section dynamically using js as the project requires to make your work more automatic and professional so that it's easy to update projects in future.you got this 👍

2022-07-20 15:43 UTC, mugishasam123 commented on index.html
> +                            <button data-modal-target="#modal" type="button">See Project</button>
- [ ] Please generate pop-up details according to the project being clicked on .not just static(fixed) details that always come up on every pop detail and that will make your site more engaging.

2022-07-20 15:43 UTC, mugishasam123 commented on style.css
> +
- [ ] Please try to stick to design as much as possible so that your work looks professional. you can do so here by trying to give your model padding to and bottom so that it does not touch screen edges.

your design:
![image](https://user-images.githubusercontent.com/90524466/180024356-8630df7d-581f-479c-8ece-b961b1561d67.png)

Figma design:
![image](https://user-images.githubusercontent.com/90524466/180024633-bb6b406b-6a63-402b-b7a4-3e526124ecc2.png)

2022-07-22 11:42 UTC, Nemwel-Boniface requested changes
## Hello @Haadiiii             :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have done a wonderful job with your portfolio modal popup :clap:. Kindly take these reviews positively as they help you better your skills as a software developer. Implementing this requirement this week sets you 20X ahead in your coming projects as what you will implement in your portfolio you will apply it in all your JavaScript projects.
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly note that according to the project requirements, the hardcoded code in the Your works section is supposed to be removed and instead generated dynamically from JavaScript. If you may be in doubt of how to achieve this, have a look at [this comment](https://github.com/rebaz36/Portfolio/pull/12#discussion_r925688836) I left for another student showing him how to achieve this. Kindly implement this as the [previous reviewer](https://github.com/Haadiiii/my-portfolio/pull/15#discussion_r925749989) had also mentioned it.


_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 11:42 UTC, Nemwel-Boniface commented on index.html
> +                        </div>
- [ ] You have done a great job with your modal popup so far :clap: However, as the [previous reviewer](https://github.com/Haadiiii/my-portfolio/pull/15#discussion_r925756855) mentioned, You are supposed to generate your popup details dynamically. Currently, your popup details is static and show the same details for all buttons which are not supposed to be the case.
- [ ] I have also realized that your desktop modal popup does not match the chosen Figma design. Kindly work on this.

**This is how your popup currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/180431147-09817a91-007d-4ed1-add3-ed75d95026b7.png)

**This is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/180431335-e3390956-5636-4be8-88b1-da2fbd805218.png)

- [ ] Kindly do so for the mobile version of your popup as well as the [previous reviewer](https://github.com/Haadiiii/my-portfolio/pull/15#discussion_r925763948) had mentioned as it still does not match the chosen Figma design.

2022-07-22 12:03 UTC, Haadiiii commented on index.html
> +                        </div>
Generating the popup dynamically is an additional requirement, as per Microverse additional requirements are optional and to be implemented outside program time.

2022-07-22 12:04 UTC, Haadiiii commented on index.html
> +                        </div>
@Nemwel-Boniface

2022-07-22 12:09 UTC, Haadiiii commented on index.html
> +                        </div>
@Nemwel-Boniface  on my laptop I see the template perfectly in all angles and pixels, I don't know why on your screen it is showing not good.

2022-07-22 12:12 UTC, Nemwel-Boniface commented on index.html
> +                        </div>
Hello @Haadiiii create a zoom call and send me the link via slack we have a look at it.

2022-07-22 12:29 UTC, Haadiiii commented on index.html
> +                        </div>
hello @Nemwel-Boniface  
I can't find you on slack and sent to you the link on zoom chat. kindly check it out.

2022-07-22 13:26 UTC, Nemwel-Boniface commented
Hello next reviewer. I have checked the project styling with the student and it looks perfect exactly as it is supposed to be in the chosen Figma design. Kindly do not penalise the student if it does not show correctly from your end.

2022-07-22 13:47 UTC, Haadiiii commented on index.html
> +                        </div>
![image](https://user-images.githubusercontent.com/104095543/180452528-7d272835-f551-4b75-882f-a8b5d2e1a4d2.png)


![image](https://user-images.githubusercontent.com/104095543/180452781-a1566cec-c967-4d32-9395-bef5e8b14d73.png)

2022-07-22 14:12 UTC, Reem-lab approved these changes
# Hi Team, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥🔥🎉🎉
<img src="https://media2.giphy.com/media/dZS9HgCrRbgA0imoak/giphy.gif"/>

## Highlights
- No Linters error ✅✅
- Good working on the requested changes ✅✅✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 14:19 UTC, merged