Microverse 3: Project
Haadiiii/my-portfolio pull request #2
Opened 2022-07-01 19:07 UTC by Haadiiii

## Mobile version Portfolio skeleton.

In this project we:

* Add HTML file with texts and images.
* Add CSS file with styling according to Figma template.
* Add Microverse README file and adjust according to the project.

2022-07-01 19:54 UTC, cwaku requested changes
Hi @Haadiiii 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
There are a few issues 🐛  that you still need to work 🛠️  on to go to the next project ⏭️  but you are almost there! 🏃🏾 

## Highlights
- [x] Very good overall template design 🥇 
- [x] Linters passed 👍🏾 
- [x] Meaningful PR description 💯 
- [x] Correvt use of Github flow ✔️ 


## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them, in order to get your project approved ✅
- [x] To make your repo more professional. I strongly suggest that you update and fill in the missing parts of your README.
  - Actually, provide the steps to have the project running locally.
  - Provide a description of the project
  - Remove sections that are not necessary for this project.

![image](https://user-images.githubusercontent.com/29071984/176960006-1da36c00-63df-42bb-a0f7-f26ffd00a2ba.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 19:54 UTC, cwaku commented on style.css
> +}
- [ ] It is a requirement that the content of each project is aligned with the flexbox. Kindly fix that 👍🏾

2022-07-01 19:54 UTC, cwaku commented on style.css
> +}
- [ ] I suggest that you add the button interactiveness. Kindly add the effects as required by the design.
- [ ] Also do the same to the buttons in the "About me" section.
![image](https://user-images.githubusercontent.com/29071984/176959247-6514b239-faa7-4d79-8f79-ac13a63a70c5.png)

2022-07-01 22:29 UTC, isaacpitwa requested changes
Hi @Haadiiii 🙂 ,

Good job so far! I know you have worked hard on implementing the changes requested by the previous reviewer. However, there is an issue that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)


## Highlights 
- All linters are passing  ✅
- Correct use of GitHub flow ✅

## Required changes ♻️ 

- [ ] As mentioned by the previous reviewer,  kindly update your README file to achieve a  more professional repository
- Actually, provide the steps to have the project running locally.
- Provide a description of the project
- Remove sections that are not necessary for this project.
      
Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 09:04 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Haadiiii       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 09:17 UTC, merged